leitura = open('pagamentos.txt', 'r', encoding='utf-8')
leitura.seek(3)
corte = (leitura.read(9))
print(corte)
leitura.close()
novo = open ('lista.txt', 'a', encoding='utf-8')
novo.write(corte +'\n')
print('----------',corte,'---------------')
novo.close()